[package]
name = "egg_recursive"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
readme.workspace = true
license.workspace = true
keywords.workspace = true

[dependencies]
egg.workspace = true
egg_recursive_derive = { path = "../egg_recursive_derive", version = "0.2.0" }
functo_rs.workspace = true

[dev-dependencies]
ordered-float.workspace = true
trybuild.workspace = true
